### ISSUE TITLE
Be able to add Default RMA settings for all vendors to comply with European regulations

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#1957]
**Is your feature request related to a problem? Please describe.**
In Europe, by law, customers have 14 days to return their product once it is received. So European marketplaces need to add their own default RMA settings for all the vendors, like we can do with the Terms & Conditions, and where the admin can select the type of warranty wanted and for how long. But, unfortunately, such a feature does not exist anymore. So for now the admin needs to verify that the vendors have well set up their RMA settings in their vendor dashboard. And even if they do, they could still change it after that the admin has verified this feature, without the admin being notified about this change.

**Describe the solution you'd like**
Be able to add Default RMA settings in Dokan Admin > RMA Settings, for all vendors to comply with European regulations, and if the option is enabled in the admin, then the RMA tab should be hidden in the vendors' dashboard. This EU RMA Default settings should contained the Default Label and Default Type, Default Lenght, Default Lenght Value, Default Lenght Duration so admin can handle the RMA settings by himself.

**Describe alternatives you've considered**
For now it is very manual. As of now, vendors can individually modify their return and warranty settings, and the duration can be set by each vendor according to their own policies. If we require a uniform warranty policy across all vendors, we need to communicate this expectation to the vendors and guide them through the process of setting up the warranty period accordingly.
We can make use of the Dokan Announcement feature to let them know but first of all, it is very manual and on top of this, vendors can still change it after that the admin has verified this feature, without the admin being notified about this change. Admin cannot spend all his time every day to verify that all vendors are respecting the right settings and that they did not modify them.

**Additional context**
Admin should be able to set up default RMA settings for all vendors like we can do for the T&C. These default Admin RMA settings could be integrated in the RMA Settings module in Dokan Admin: https://ibb.co/rxs8CSH
Here is a picture of the actual RMA settings module for vendors so you can see the field missing in the Admin module: https://ibb.co/ZfXLt4D

**Comment by Sophie-2e** [comment]
@imtiaz-pranto where are we with this? It is opened since August 2023 and will really simplify the life of the admin.

**Comment by Sophie-2e** [comment]
Hello @imtiaz-pranto hope you're well, any news on this must-have feature for european users?

**Comment by Sophie-2e** [comment]
What is the ETA on this @imtiaz-pranto?

**Comment by imtiaz-pranto** [comment]
Dear @Sophie-2e, while the proposed feature to add default RMA settings for compliance with European regulations has clear benefits, its implementation poses several challenges. Addressing these complexities would necessitate a thorough redesign of the existing RMA settings module, which is why it was delayed. 

Let me give you three reasons: 
1. Dokan allows vendors to customize their return and warranty settings. Implementing a uniform default RMA setting might restrict vendors' ability to tailor their policies to their specific needs.

2. While the 14-day return policy is standard in Europe, other regions have different regulations. The system would need to be adaptable to accommodate these varying requirements, including cross border marketplaces.

3. Forcing a uniform RMA policy might not be well-received by all vendors, especially those who have their own established return and warranty practices. Balancing regulatory compliance with vendor preferences would be challenging.

We get why having default RMA settings would be super helpful, especially with the 14-day return policy in Europe. That said, we're definitely considering how to make this work and will be looking into it as we plan our future updates. As of now, I cannot give a fixed date for this, but I will let you know the update. Your feedback is important to us, and we're committed to finding a solution that works for everyone. 
Thanks for the suggestion!

**Comment by Sophie-2e** [comment]
Hello @imtiaz-pranto, great thank you very much for the explanation and ETA, indeed it needs to be an optional feature to fit other Dokan Users' cases who don't need a minimum time period. And thank you for considering this feature in the future. Let's make Dokan greater together 💯👌

**Comment by Paradoxalissue** [comment]
> Hello [@imtiaz-pranto](https://github.com/imtiaz-pranto), actually I could code a permanent solution for my use case so I will go ahead and close this GitHub as it does not seem to be a prio for Dokan users ;-)

Hi Sophie, so you found a solution to force the RMA by default for all the vendors?
I have the same issue that you faced. Would it be possible to share the code you created to fix this problem?
Thank you very much !
