### ISSUE TITLE
Dokan mobile comatibiltiy issue with buddyboss theme

### ISSUE THREAD

**Issue by sumitsk6055** [getdokan/dokan#2003]
### Bug Description

We are using Woocommerce bookings plugin to provide vendors a factility to create bookable products, But under vendor dashboard When bookings page is opened and Buddyboss theme is active the mobile version of page is not comming up properly and getting completely broken 

### Step To Reproduce

1. Install WooCommerce Bookings Plugin
2. Activate buddyboss theme
3. Go to vendor dashboard
4. Open Bookings Tab
5. Open mobile Version of the page
![image](https://github.com/getdokan/dokan/assets/96922674/e46de25b-387e-47e7-b90a-c8696639dabb)
![image](https://github.com/getdokan/dokan/assets/96922674/40d86ace-55b2-4a75-8761-c4aff90196f8)

### Expected Behaviour

It should show up in proper formatted way

### Actual Behaviour

Getting broken layout

### Environment (please complete the following information)

```shell
1. Dokan Version: [e.g. v3.8.2]
2. Dokan Pro Version: [e.g. v3.8.3]
3. WooCommerce Version: [e.g. v8.1.1]
4. Browser [e.g. chrome, safari]
5. Current Theme: [e.g. Buddyboss]
```

**Comment by Eh-Mr-SK** [comment]
This issue is still not fixed

**Comment by prottoy210385** [comment]
Hello @Eh-Mr-SK,

Since Dokan Booking is a premium feature of Dokan, please create a ticket through your Dokan.co account here: https://app.dokan.co/support/create. We are unable to provide assistance for Dokan premium features on the Dokan Lite repository.

After creating a ticket, our support engineers will investigate the issue with the Woocommerce Bookings plugin under the vendor dashboard. If they can replicate the issue on their end, they will proceed further to resolve it.

Thank you for your understanding.

Kind regards,
