### ISSUE TITLE
Issue with displaying the correct withdrawal charge amount on the vendor dashboard

### ISSUE THREAD

**Issue by sazz-pranto** [getdokan/dokan#2303]
### Bug Description

**Description:**
If period (.) is selected as the thousand separator and prices are set to be displayed without any decimal point values in WooCommerce currency settings, it displays only the **first digit** of the withdrawal charge amount if the amount is more than three digits.

### Step To Reproduce

1. Go to WP admin dashboard > WooCommerce > Settings > General screen
2. Set the currency options as described above
3. Go to WP admin dashboard > Dokan > Settings > Withdraw Options screen and set a flat rate withdrawal charge for bank transfer as shown in this screenshot: https://snipboard.io/Fs8yA1.jpg
4. Go to the vendor dashboard, proceed to make a withdrawal request, and observe the withdrawal charge. 

### Expected Behaviour

The correct withdrawal amount should appear regardless of the currency settings in WooCommerce.

### Actual Behaviour

Please have a look at this video: https://d.pr/v/XuUKTJ

### Environment (please complete the following information)

```shell
1. Dokan Version: 3.11.3
2. WooCommerce Version: 9.0.2
3. WordPress version: 6.5.5
```

**Comment by MdAsifHossainNadim** [comment]
@sazz-pranto Brother, We discourage to use decimal precision as thousand separator. Because, in woocommerce accounting object we can't detect decimal precision as thousand seperator.
<img width="357" alt="Screenshot 2024-07-04 at 10 03 37 AM" src="https://github.com/getdokan/dokan/assets/90011088/ca4bafa2-e6f5-4db0-a4e1-63ccd62075fa">
<img width="575" alt="Screenshot 2024-07-04 at 10 03 20 AM" src="https://github.com/getdokan/dokan/assets/90011088/c016c793-d810-4c6a-84f1-b6deda9b1e92">

**Comment by J-H-Mojumder** [comment]
@MdAsifHossainNadim bhai As far as I can recall, there is a function that returns the decimal separator named `wc_get_price_decimal_separator()` that returns the value of the site's `_options` table's `woocommerce_price_decimal_sep` metakey's value. For the thousand separator, the function is `wc_get_price_thousand_separator()`.

Am I missing anything?

**Comment by MdAsifHossainNadim** [comment]
@J-H-Mojumder Brother, the problem is not only related to rendering. We are using WooCommerce `account.formatMoney` to receive the formatted money and then we are deducting the money from the receivable amount. Now, when we are using (.) separator as thousand separators then WooCommerce `account.formatMoney` cannot detect the correct thousand value due to decimal conflict. We therefore encourage not to use decimal separators as thousands or currency symbols via prohibition message on the relevant settings.

**Comment by J-H-Mojumder** [comment]
@MdAsifHossainNadim bhai using (.) as a thousand separator is an accounting rule in many countries like Germany, Italy, Switzerland, Spain, France etc. If we have any limitations regarding this, we might need to change our approach towards the matter. Also, it is a default feature of WooCommerce. So, this will not look good to discourage users not to use this functionality.

I hope this will explain the scenario and the necessity of the matter.
