### ISSUE TITLE
Button Background color comes from nowhere

### ISSUE THREAD

**Issue by Orrigine** [getdokan/dokan#2327]
### Bug Description

For a long time, I've seen in the Dashboard product creation, the little buttons for the markdown in the description sections have a background color which is a primary color that exists, but I've never wanted to have this color here, and never choosed to have it here.
![image](https://github.com/user-attachments/assets/e28f6543-8fcf-479a-8796-c6389f33505f)
I've seen that this color is inherited by a rule that is on the 

I've found the css that does this, but I don't know where it comes from and how to change it.

### Step To Reproduce

1. Go to the Vendor Dashboard of Dokan
2. Click on Products
3. Click on Add a Product
4. See the color of the buttons for markdown in the description section

### Expected Behaviour

I would like to be able to change this color instead of having my default primary one _which in this case is not a big deal_

### Actual Behaviour

The actual behaviour is the buttons displayed in the color of my primary one, which is here a variable in the css
```
.elementor-kit-35 button,.elementor-kit-35 input[type="button"],.elementor-kit-35 input[type="submit"],.elementor-kit-35 .elementor-button {
    color: #FFFFFF;
    background-color: var( --e-global-color-primary ); _#1c244b_
}
```

### Environment (please complete the following information)

```shell
1. Dokan Version: [v3.11.4]
2. Dokan Pro Version: [v3.11.2]
3. WooCommerce Version: [v9.1.4]
4. Browser [Brave]
5. Current Theme: [Dokani]
```

**Comment by mr-gausulazam** [comment]
Hello @Orrigine ,

I hope you're doing well.

The product description button background color is set to white by default in our plugin. If this background color has been changed, it might be due to a different plugin, custom code, or your theme settings. However, I don't see any background color on my local site. This is the reference: https://snipboard.io/rcXwDJ.jpg

I noticed that you're using the Dokan Premium plugin on your website. If you're facing issues, you can reach out to us through this link: https://app.dokan.co/support/create. Our official support team will be happy to assist you in resolving the matter.

Thank you for your understanding.

Best MGA,
