### ISSUE TITLE
Stripe Express integration error - parameter_unknown - description

### ISSUE THREAD

**Issue by dan504301** [getdokan/dokan#2330]
### Bug Description

After the 3.11.4 update, more exactly after this update ( – **update:** Improved error handling in Dokan Stripe Express when failed order updates.) we have a new integration error.

### Steps to replicate (guest mode checkout):

**1.First, I tried a test payment with a generic decline. The payment failed.**

**2.Then, I tried the payment with a different valid card. This new integration error occurred and the payment succeeded.**

In the end, the payment went through, but it is worth an investigation by the developer team.

![355934793-a6bb1e2b-9f3c-4444-8b4c-4362a49495d4](https://github.com/user-attachments/assets/57210823-ebf5-4651-b39f-08d3cdbafaa9)

**Comment by mralaminahamed** [comment]
@dan504301 Thanks for reporting this issue and providing detailed steps to reproduce. We've investigated the problem and here's what we found:

1. **Root cause**: The "parameter_unknown - description" error occurs because we're sending unnecessary parameters (description, email, preferred_locales, name) when retrieving Stripe customer data in guest mode.

2. **Fix**: We've developed a solution that removes these unsupported parameters from the API request. This should resolve the error while maintaining successful payment processing.

3. **Status**: The fix is currently undergoing thorough development review and testing to ensure it doesn't introduce any new issues.

4. **Next steps**: Once development review and testing are complete, we'll include this fix in our future release. We'll update this issue when it's available.

While it's good that payments are still going through, we appreciate you bringing this to our attention. It helps us improve Dokan's stability and user experience.

Thanks again for your contribution to improving Dokan!

**Comment by dan504301** [comment]
@mralaminahamed, thank you!

The Stripe Express module will be flawless with this final fix.

**Comment by dan504301** [comment]
@mralaminahamed, another integration error related to this update.

**resource_missing - id
No such charge:** 

<img width="437" alt="Captură de ecran din 2024-08-17 la 11 11 16" src="https://github.com/user-attachments/assets/e7729da2-ec51-4911-a726-8a2fd855716c">

The payment was initially attempted with a card, but when that failed, the client used Google Pay. The payment was successful, but we received a duplicate order email.

The first order remained in the processing stage in WooCommerce, yet we still received a successful order email for the initial, unsuccessful attempt.

Switching to Google Pay triggered another successful order with a new order number.

I hope this makes sense.

**Comment by dan504301** [comment]
@mralaminahamed, another integration error related to this update.

**resource_missing - id** 

**No such charge:**

<img width="437" alt="Captură de ecran din 2024-08-17 la 11 11 16" src="https://github.com/user-attachments/assets/ade15888-b3d7-4d1d-b5a3-b7969e7ed937">


1. The payment was initially attempted with a card (or Google Pay, I'm not sure), but when that failed, the client used Google Pay.
2. The payment was successful, but we received a duplicate order email.
3. The first order remained in the processing stage in WooCommerce, yet we still received a successful order email for the initial, unsuccessful attempt.
4. Switching to Google Pay triggered another successful order with a new order number.

I hope this makes sense, if not I will try to replicate the exact steps on a latter date.

The client never leaved the checkout page.

I don't know if the fix (for the initial integration error - parameter_unknown - description) will also address this issue.

**Comment by mralaminahamed** [comment]
@dan504301, thank you for reporting this issue and providing detailed steps to reproduce. We are currently investigating the problem and will update you once we have any fix or more information.

**Comment by dan504301** [comment]
@mralaminahamed @shohag121 , were you able to replicate and fix the second issue with the duplicate email?

It happened again today.

Thank you!
