### ISSUE TITLE
Dokan export  products are not mobile friendly 

### ISSUE THREAD

**Issue by Eh-Mr-SK** [getdokan/dokan#2359]
### Bug Description

While trying to export products from Dokan in mobile its not mobile responsive 
![image](https://github.com/user-attachments/assets/8f760332-932f-4b37-b309-1f956756f7c1)

### Step To Reproduce

1. Go to 'Dokan > Vendor Dashboard'
2. Click on 'Tools'
3. Scroll down to ' Export '
4. See error (Perform in mobile)

### Expected Behaviour

It should have looked better responsive in mobile

### Actual Behaviour

Boxes are overflowing 
![image](https://github.com/user-attachments/assets/d1793a99-7931-4c68-b8f9-d37150121f53)

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.12.0]
2. Dokan Pro Version: [v3.12.0 ]
3. WooCommerce Version: [9.2.3]
4. Browser [Chrome]
5. Current Theme: [Tested on Buddyboss & Woodmart]
```

**Comment by sazz-pranto** [comment]
Thanks for bringing this to our attention, @Eh-Mr-SK. Since this is a **Pro** feature, we will create an issue in the GitHub repository (private) of **Dokan Pro**. Our development team will take further steps to make the Export/Import section responsive to different screen sizes. 

With that being said, I am closing this issue. Again, we appreciate your contribution!
