### ISSUE TITLE
Vendor Dashboard Incorrect Earning Amount

### ISSUE THREAD

**Issue by Adrian-Albanese** [getdokan/dokan#2399]
### Bug Description

A vendor has made a sale for $15 and his dashboard reports an earning amount of -$15.69.

Net sale was $15, with a commission rate of 10% applied, he should be seeing an earning amount of +$13.50. In addition, the $0.69 of payment gateway processing fee should not be applied to his earning amount.

### Expected Behaviour

Expected: $15 net sale @ 10% commission = **+**$13.50 earnings amount on vendor dashboard

### Actual Behaviour

Actual: $15 net sale @ 10% commission = **-**$15.69 earnings amount on vendor dashboard

### Environment

1. Dokan Version: v3.12.4
2. WooCommerce Version: 9.3.3
3. Browser: chrome
4. Current Theme: Blocksy

**Comment by Fayeakuzzamantonmoy** [comment]
Hello @Adrian-Albanese, 

Thank you for bringing this issue to our attention. We’ve attempted to reproduce it on our end but were unable to do so, indicating that this may be a site-specific issue. To identify the root cause, we’ll need to investigate your site directly. Unfortunately, we’re unable to provide this level of assistance through the public forum. Kindly raise a support ticket, and our team will be happy to assist you further. You can submit a ticket by [following this link](https://app.dokan.co/login).

We appreciate your understanding. 

Thanks!
